export const ICONS = {
  VEHICLE: "car-outline",
  MAINTENANCE: "build-outline",
  PART: "construct-outline",
  LOGOUT: "log-out-outline",
  ADD: "add-circle-outline",
  GOOGLE: "logo-google",
  IMAGE: "image-outline",
  EDIT: "pencil",
  DELETE: "trash",
  CASH: "cash-outline",
  DOCUMENT: "document-text-outline",
  ARROW_RIGHT: "chevron-forward",
  ARROW_DOWN: "chevron-down",
  ARROW_UP: "chevron-up",
  ARROW_BACK: "chevron-back",
  FILE: "document-outline",
  CLOSE_CIRCLE: "close-circle",
  DATE: "calendar-outline",
  SCHEDULE: "hourglass-outline",
  NOTIFICATION: "notifications-outline",
  MILEAGE: "speedometer-outline",
  MORE_VERTICAL: "ellipsis-vertical",
  RELOAD: "reload-outline",
  POWER: "power-outline",
  CHECK: "checkmark"
} as const;
