export const ICONS = {
  VEHICLE: "car-outline",
  MAINTENANCE: "build-outline",
  PART: "construct-outline",
  LOGOUT: "log-out-outline",
  ADD: "add-circle-outline",
  GOOGLE: "logo-google",
  IMAGE: "image-outline",
  EDIT: "pencil",
  DELETE: "trash",
  CASH: "cash-outline",
  DOCUMENT: "document-text-outline",
  ARROW_RIGHT: "chevron-forward",
  FILE: "document-outline",
  CLOSE_CIRCLE: "close-circle",
} as const;
